### ISSUE TITLE
Missing XOAuth2 entry value for ’xoauth2_token_url’

### ISSUE THREAD

**Issue by matteo-l** [ccrusius/auth-source-xoauth2#6]
I'm unable to send email from emacs 27.1 after installing auth-source-xoauth2.
[messages.txt](https://github.com/ccrusius/auth-source-xoauth2/files/5682979/messages.txt)

I created the the tokens folowing the instructions and added them to ~/.password-store/smtp.gmail.com:465/MYEMAIL@gmail.com.gpg, the file content is

    mypassword
    xoauth2_token_url: https://accounts.google.com/o/oauth2/token
    xoauth2_client_id: REDACTED
    xoauth2_client_secret: REDACTED
    xoauth2_refresh_token: REDACTED

If I start `emacs -q` and evaluate the following code in `*scratch*`

    (package-initialize)
    (require 'auth-source-xoauth2)
    (setq auth-source-xoauth2-creds #'auth-source-xoauth2-pass-creds)
    (auth-source-xoauth2-enable)

    (setq send-mail-function #'smtpmail-send-it
          smtpmail-smtp-user "MYEMAIL@gmail.com"
          smtpmail-default-smtp-server "smtp.gmail.com"
          smtpmail-smtp-server "smtp.gmail.com"
          smtpmail-smtp-service 465
          smtpmail-stream-type 'ssl)

    (setq auth-source-debug t)

in the *Messages* buffer I get the error message in the subject. I attached the whole content of the *Messages* buffer.
[messages.txt](https://github.com/ccrusius/auth-source-xoauth2/files/5682981/messages.txt)

The email setup works if i put an application-specific password in ~/.authinfo.gpg and disable

**Comment by simurgh9** [comment]
I figured this out, look at the definition of

```lisp
(defun auth-source-xoauth2-pass-creds (host user port)
  (when-let ((entry (auth-source-xoauth2-pass--find-match host user port)))
    (when-let
        ((url (auth-source-xoauth2--pass-get "xoauth2_token_url" entry))
[snip]
```

`(auth-source-xoauth2--pass-get "xoauth2_token_url" entry)` breaks because the function `auth-source-xoauth2--pass-get` expects the entry to be an entry-name whereas `(auth-source-xoauth2-pass--find-match host user port)` returns the entry-data: `((secret . "password"), ("xoauth2_token_url" . "https://www..."), ...)`!

By the way, there is some funny business involved with `auth-source-xoauth2-pass--find-match` which conditionally calls `auth-source-pass--find-match` with three or two arguments.

```lisp
(cl-defun auth-source-xoauth2-pass--find-match (host user port)
  "Find password for given HOST, USER, and PORT.
This is a wrapper around `auth-pass--find-match`, which is needed
because the MELPA and Emacs 26 versions of the function accept
a different number of arguments."
  (condition-case nil
      (auth-source-pass--find-match host user port)
    (wrong-number-of-arguments
     (auth-source-pass--find-match host user))))
```
If I do `C-h f auth-source-pass--find-match`, I get,

```
auth-source-pass--find-match is a compiled Lisp function in
‘auth-source-pass.el’.

(auth-source-pass--find-match HOST USER PORT)

Return password-store entry data matching HOST, USER and PORT.

Disambiguate between user provided inside HOST (e.g., user@server.com) and
inside USER by giving priority to USER.  Same for PORT.

[back]
```

But when I click on `auth-source-pass.el` and read the source of `auth-source-pass--find-match`,

```lisp
(defun auth-source-pass--find-match (host user)
  "Return a password-store entry name matching HOST and USER.
If many matches are found, return the first one.  If no match is
found, return nil."
[snip]
```

Wait what? The documentation and the definition contradict. I am guessing the function `auth-source-pass--find-match` is getting redefined somewhere else? Originally, it returned the entry-name and not entry data. But as the documentation points out, it is now returning entry-data!

So what is the fix? Process the entry data in `defun auth-source-xoauth2-pass-creds`, I changed it to this:

```lisp
(defun auth-source-xoauth2-pass-creds (host user port)
  (when-let ((entry (auth-source-xoauth2-pass--find-match host user port)))
    (when-let
        ((url (cdr (assoc "xoauth2_token_url" entry)))
         (id (cdr (assoc "xoauth2_client_id" entry)))
         (secret (cdr (assoc "xoauth2_client_secret" entry)))
         (token (cdr (assoc "xoauth2_refresh_token" entry))))
      (list
       :token-url url
       :client-id id
       :client-secret secret
       :refresh-token token))))
```
Now it works. Someone should really fix `auth-source-pass.el`!
